import { db } from "./db";
import { brands } from "@shared/schema";

const brandList = [
  {
    name: "Apple",
    supportEmail: "support@apple.com",
    supportPhone: "+1-800-692-7753",
    website: "https://www.apple.com/support/",
    category: "Informática",
  },
  {
    name: "Samsung",
    supportEmail: "support@samsung.com",
    supportPhone: "+351-808-207-267",
    website: "https://www.samsung.com/pt/support/",
    category: "Eletrodomésticos",
  },
  {
    name: "LG",
    supportEmail: "apoio.cliente@lge.com",
    supportPhone: "+351-707-505-454",
    website: "https://www.lg.com/pt/support",
    category: "Eletrodomésticos",
  },
  {
    name: "Sony",
    supportEmail: "info@sony.pt",
    supportPhone: "+351-707-780-785",
    website: "https://www.sony.pt/support",
    category: "Televisão e Áudio",
  },
  {
    name: "Bosch",
    supportEmail: "bshp.repacao@bshg.com",
    supportPhone: "+351-214-250-730",
    website: "https://www.bosch-home.pt/servico",
    category: "Eletrodomésticos",
  },
  {
    name: "Siemens",
    supportEmail: "siemens-pt@bshg.com",
    supportPhone: "+351-214-250-700",
    website: "https://www.siemens-home.bsh-group.com/pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Microsoft",
    supportEmail: "support@microsoft.com",
    supportPhone: "+351-21-366-5100",
    website: "https://support.microsoft.com/",
    category: "Informática",
  },
  {
    name: "Dell",
    supportEmail: "tech_support@dell.com",
    supportPhone: "+351-707-788-788",
    website: "https://www.dell.com/support/",
    category: "Informática",
  },
  {
    name: "HP",
    supportEmail: "support@hp.com",
    supportPhone: "+351-707-222-000",
    website: "https://support.hp.com/",
    category: "Informática",
  },
  {
    name: "Xiaomi",
    supportEmail: "service.pt@xiaomi.com",
    supportPhone: "+351-308-810-456",
    website: "https://www.mi.com/pt/service/",
    category: "Telefones",
  },
  {
    name: "Teka",
    supportEmail: "servico.cliente@teka.pt",
    supportPhone: "+351-256-200-100",
    website: "https://www.teka.pt/servico-tecnico/",
    category: "Eletrodomésticos",
  },
  {
    name: "Ariston",
    supportEmail: "info@ariston.pt",
    supportPhone: "+351-213-180-900",
    website: "https://www.ariston.com/pt-PT/",
    category: "Eletrodomésticos",
  },
  {
    name: "AEG",
    supportEmail: "rma.pt@eletrolux.com",
    supportPhone: "+351-210-304-261",
    website: "https://www.aeg.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Avenzo",
    supportEmail: "sat@avenzo.biz",
    supportPhone: "+351-800-800-800",
    website: "https://www.avenzo.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Beko",
    supportEmail: "servico.clientes@beko.pt",
    supportPhone: "+351-214-250-650",
    website: "https://www.beko.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Bluesens",
    supportEmail: "posvenda@bluesens.com",
    supportPhone: "+351-226-108-030",
    website: "https://www.bluesens.com/",
    category: "Eletrodomésticos",
  },
  {
    name: "Candy",
    supportEmail: "service.portugal@candy-hoover.com",
    supportPhone: "+351-214-250-600",
    website: "https://www.candy.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Hoover",
    supportEmail: "service.portugal@candy-hoover.com",
    supportPhone: "+351-214-250-600",
    website: "https://www.hoover.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Haier",
    supportEmail: "service.pt@haier.com",
    supportPhone: "+351-214-250-500",
    website: "https://www.haier.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Confortec",
    supportEmail: "geral@liana.com.pt",
    supportPhone: "+351-214-250-400",
    website: "https://www.confortec.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Telefac",
    supportEmail: "geral@liana.com.pt",
    supportPhone: "+351-214-250-300",
    website: "https://www.telefac.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Newpool",
    supportEmail: "geral@liana.com.pt",
    supportPhone: "+351-214-250-350",
    website: "https://www.newpool.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Cata",
    supportEmail: "junis@junis.pt",
    supportPhone: "+34-938-521-818",
    website: "https://www.cata.com/pt-es/",
    category: "Eletrodomésticos",
  },
  {
    name: "Casio",
    supportEmail: "margaridadias@casio.pt",
    supportPhone: "+351-210-304-200",
    website: "https://www.casio-europe.com/pt/",
    category: "Eletrónicos",
  },
  {
    name: "Crown",
    supportEmail: "spv.crowneurope@gmail.com",
    supportPhone: "+351-214-250-200",
    website: "https://www.crown.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Celly",
    supportEmail: "devoluciones@esprinet.com",
    supportPhone: "+351-214-250-150",
    website: "https://www.celly.pt/",
    category: "Eletrónicos",
  },
  {
    name: "Cecotec",
    supportEmail: "suporte@cecotec.pt",
    supportPhone: "+351-300-057-275",
    website: "https://www.cecotec.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Delta",
    supportEmail: "clientes.retail@mydeltaq.com",
    supportPhone: "+351-214-250-050",
    website: "https://www.delta.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Delba",
    supportEmail: "assistenciatecnica@sacrofil.pt",
    supportPhone: "+351-214-250-000",
    website: "https://www.delba.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Daitsu",
    supportEmail: "geral@servitis.pt",
    supportPhone: "+351-214-250-500",
    website: "https://www.daitsu.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Ufesa",
    supportEmail: "servicosat@ufesa.pt",
    supportPhone: "+351-214-250-750",
    website: "https://www.ufesa.es/?lang=pt-pt",
    category: "Eletrodomésticos",
  },
  {
    name: "Epson",
    supportEmail: "apoio_clientes@epson.pt",
    supportPhone: "+351-707-222-000",
    website: "https://www.epson.pt/pt_PT/support",
    category: "Impressoras e Periféricos",
  },
  {
    name: "eMachines",
    supportEmail: "support_pt@emachines.com",
    supportPhone: "+351-214-156-700",
    website: "https://www.emachines.com/ec/pt/PT/content/home.html",
    category: "Computadores",
  },
  {
    name: "e-star",
    supportEmail: "estar@atinformatica.pt",
    supportPhone: "+351-229-059-999",
    website: "https://www.atinformatica.pt/",
    category: "Computadores",
  },
  {
    name: "Fagor",
    supportEmail: "contacto@fagorelectrodomestico.com",
    supportPhone: "+351-707-502-207",
    website: "https://www.fagorelectrodomestico.pt/contactos",
    category: "Eletrodomésticos",
  },
  {
    name: "Electrolux",
    supportEmail: "electrolux.service@electrolux.pt",
    supportPhone: "+351-308-813-383",
    website: "https://www.electrolux.pt/support/contact-us/",
    category: "Eletrodomésticos",
  },
  {
    name: "Emtec",
    supportEmail: "support.emtec@dexxon.eu",
    supportPhone: "+33-147-291-900",
    website: "https://www.emtec-international.com/",
    category: "Produtos Tecnológicos",
  },
  {
    name: "Energizer",
    supportEmail: "geral@tametgroup.com",
    supportPhone: "+351-229-059-430",
    website: "https://energizer.com/eu/portugal/",
    category: "Baterias e Iluminação",
  },
  {
    name: "Energysytem",
    supportEmail: "garantias.telenets.es",
    supportPhone: "+34-934-110-700",
    website: "https://www.energysytem.es/",
    category: "Eletrónicos",
  },
  {
    name: "Flama",
    supportEmail: "sat@flama.pt",
    supportPhone: "+351-808-250-178",
    website: "https://www.flama.pt",
    category: "Eletrodomésticos",
  },
  {
    name: "Fujitsu",
    supportEmail: "portugal.helpdesk@ts.fujitsu.com",
    supportPhone: "+351-217-244-400",
    website: "https://www.fujitsu.com/pt/",
    category: "Computadores",
  },
  {
    name: "Growing",
    supportEmail: "geral@grow.com.pt",
    supportPhone: "+351-211-303-000",
    website: "https://www.grow.com.pt/",
    category: "Equipamentos Industriais",
  },
  {
    name: "Groundtec",
    supportEmail: "groundtec@groundtec.com.pt",
    supportPhone: "+351-227-133-368",
    website: "https://www.groundtec.com.pt/",
    category: "Equipamentos Construtivos",
  },
  {
    name: "Lovit",
    supportEmail: "lovit@lovit.com.pt",
    supportPhone: "+351-227-133-368",
    website: "https://www.lovit.com.pt/",
    category: "Equipamentos",
  },
  {
    name: "Grunkel",
    supportEmail: "repuestos@cointer.com",
    supportPhone: "+34-954-182-404",
    website: "https://grunkel.com",
    category: "Eletrónicos",
  },
  {
    name: "Hisense",
    supportEmail: "atencaoaocliente@hisenseiberia.com",
    supportPhone: "+351-800-181-818",
    website: "https://www.hisense.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Hitachi",
    supportEmail: "contacto@hitachi.pt",
    supportPhone: "+351-212-199-900",
    website: "https://www.hitachi.eu/en/",
    category: "Eletrodomésticos",
  },
  {
    name: "Insys",
    supportEmail: "suporte.tecnico@insys.pt",
    supportPhone: "+351-234-340-880",
    website: "https://www.insys.pt/",
    category: "Computadores",
  },
  {
    name: "Indesit",
    supportEmail: "apoio@indesit.pt",
    supportPhone: "+351-219-406-200",
    website: "https://www.indesit.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Whirlpool",
    supportEmail: "apoio_consumidor@email.whirlpool.com",
    supportPhone: "+351-707-203-204",
    website: "https://www.whirlpool.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Infiniton",
    supportEmail: "contacto@infiniton.pt",
    supportPhone: "+34-958-087-169",
    website: "https://infiniton.pt/",
    category: "Eletrónicos",
  },
  {
    name: "Jocca",
    supportEmail: "atencionalcliente@jocca.es",
    supportPhone: "+34-976-472-047",
    website: "https://www.joccashop.com/pt/",
    category: "Eletrónicos",
  },
  {
    name: "Kenwood",
    supportEmail: "contacto@kenwoodworld.com",
    supportPhone: "+351-707-201-468",
    website: "https://www.kenwoodworld.com/pt-pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Loewe",
    supportEmail: "customerservice@loewe.com",
    supportPhone: "+49-9261-99-500",
    website: "https://www.loewe.com/",
    category: "Eletrónicos",
  },
  {
    name: "Lenovo",
    supportEmail: "pt-support@lenovo.com",
    supportPhone: "+351-213-665-231",
    website: "https://www.lenovo.com/pt/pt/",
    category: "Computadores",
  },
  {
    name: "Manta",
    supportEmail: "contacto@manta.pt",
    supportPhone: "+351-300-000-000",
    website: "https://manta.pt/",
    category: "Eletrónicos",
  },
  {
    name: "Meireles",
    supportEmail: "contactos@meireles.pt",
    supportPhone: "+351-256-000-000",
    website: "https://www.meireles.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Memup",
    supportEmail: "suporte@memup.pt",
    supportPhone: "+351-300-000-000",
    website: "https://memup.pt/",
    category: "Eletrónicos",
  },
  {
    name: "Maxcom",
    supportEmail: "obsluga.klienta@maxcom.pl",
    supportPhone: "+48-325-070-0",
    website: "https://pt.maxcommobile.eu/",
    category: "Telemóveis",
  },
  {
    name: "Neckar",
    supportEmail: "suporte@neckar.pt",
    supportPhone: "+351-300-000-000",
    website: "https://neckar.pt/",
    category: "Eletrónicos",
  },
  {
    name: "Nardi",
    supportEmail: "info@nardioutdoor.com",
    supportPhone: "+39-444-422-100",
    website: "https://www.nardioutdoor.com/",
    category: "Móveis",
  },
  {
    name: "Nintendo",
    supportEmail: "service@nintendo.de",
    supportPhone: "+351-211-129-511",
    website: "https://www.nintendo.com/pt-pt/",
    category: "Consolas",
  },
  {
    name: "NGS",
    supportEmail: "suporte@ngs.eu",
    supportPhone: "+351-300-000-000",
    website: "https://www.ngs.eu/pt/",
    category: "Eletrónicos",
  },
  {
    name: "Nilox",
    supportEmail: "suporte@nilox.pt",
    supportPhone: "+351-300-000-000",
    website: "https://nilox.pt/",
    category: "Eletrónicos",
  },
  {
    name: "Olympus",
    supportEmail: "pt.support@olympus.com",
    supportPhone: "+351-300-000-000",
    website: "https://www.olympus.pt/",
    category: "Câmaras",
  },
  {
    name: "Orima",
    supportEmail: "suporte@orima.pt",
    supportPhone: "+351-300-000-000",
    website: "https://orima.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Philips",
    supportEmail: "apoio@philips.pt",
    supportPhone: "+351-800-780-903",
    website: "https://www.philips.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Primux",
    supportEmail: "contacto@primux.es",
    supportPhone: "+34-988-120-120",
    website: "https://www.primux.es/",
    category: "Eletrónicos",
  },
  {
    name: "Prixton",
    supportEmail: "suporte@prixton.pt",
    supportPhone: "+351-300-000-000",
    website: "https://prixton.pt/",
    category: "Eletrónicos",
  },
  {
    name: "PlayStation",
    supportEmail: "suportederede@pt.playstation.com",
    supportPhone: "+351-211-121-813",
    website: "https://www.playstation.com/pt-pt/",
    category: "Consolas",
  },
  {
    name: "Rowenta",
    supportEmail: "apoio@rowenta.pt",
    supportPhone: "+351-214-237-700",
    website: "https://www.rowenta.pt/",
    category: "Eletrodomésticos",
  },
  {
    name: "Remington",
    supportEmail: "apoio@remington.pt",
    supportPhone: "+351-800-100-058",
    website: "https://pt.remington-europe.com/",
    category: "Eletrónicos",
  },
  {
    name: "Russell Hobbs",
    supportEmail: "apoio@russellhobbs.pt",
    supportPhone: "+351-800-100-058",
    website: "https://pt.russellhobbs.com/",
    category: "Eletrodomésticos",
  },
  {
    name: "SPC",
    supportEmail: "support@spc.es",
    supportPhone: "+351-308-805-245",
    website: "https://www.spcstore.pt/",
    category: "Eletrónicos",
  },
  {
    name: "StreamSystem",
    supportEmail: "suporte@streamsystem.pt",
    supportPhone: "+351-300-000-000",
    website: "https://streamsystem.pt/",
    category: "Eletrónicos",
  },
  {
    name: "TomTom",
    supportEmail: "pt-support@tomtom.com",
    supportPhone: "+351-800-780-277",
    website: "https://www.tomtom.com/pt-pt/",
    category: "GPS",
  },
  {
    name: "TNB",
    supportEmail: "contacto@tnb.pt",
    supportPhone: "+351-707-917-070",
    website: "https://tnb.pt/",
    category: "Serviços",
  },
  {
    name: "Xbox",
    supportEmail: "support@xbox.com",
    supportPhone: "+351-800-209-175",
    website: "https://www.xbox.com/pt-pt/",
    category: "Consolas",
  },
  {
    name: "Toshiba",
    supportEmail: "suporte@toshiba.pt",
    supportPhone: "+351-707-266-266",
    website: "https://www.toshiba.eu/",
    category: "Eletrónicos",
  },
  {
    name: "SVAN",
    supportEmail: "info@svanelectro.com",
    supportPhone: "+351-300-305-065",
    website: "https://svanelectro.com/",
    category: "Eletrodomésticos",
  },
  // Marca de Teste
  {
    name: "Teste - Garantia Manager",
    supportEmail: "juliomcm@hotmail.com",
    supportPhone: "+351-300-000-000",
    website: "https://www.garantiamanager.pt/",
    category: "Testes",
  },
];

async function seed() {
  try {
    // Clear existing brands
    await db.delete(brands);
    
    // Insert all brands
    await db.insert(brands).values(brandList);
    console.log(`✅ Seeded ${brandList.length} brands to database!`);
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

seed();
